name: pay_reminder
description: "Pay Reminder"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.2
  flutter_riverpod: ^2.6.1
  intl: ^0.20.1
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  drift_dev: ^2.23.1

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
