name: pay_reminder
description: "Never Forgett - Payment Reminder App"

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_storage: ^12.4.0
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^3.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  home_widget: ^0.7.0
  intl: ^0.20.1
  quick_actions: ^1.1.0
  shared_preferences: ^2.3.5
  table_calendar: ^3.0.9
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  drift_dev: ^2.23.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
