name: pay_reminder
description: "Never Forgett - Payment Reminder App"

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ^3.6.2

dependencies:
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  flutter_slidable: ^4.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  home_widget: ^0.7.0+1
  intl: ^0.19.0
  local_auth: ^2.3.0
  quick_actions: ^1.1.0
  shared_preferences: ^2.5.2
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  table_calendar: ^3.0.9
  timezone: ^0.10.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.0
  drift_dev: ^2.25.2
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
